### PR TITLE
db_lmdb: fix stray characters in migration logs

### LINKED ISSUE #149: stray char in migration logs still
Reported by @nahuhh even after applying #128:

```
2025-10-06 17:25:06.239 I Setting up a locked outputs table (step 1/2 of the full-chain membership proof migration) 
2025-10-06 17:25:59.909 I Setting up a merkle tree using existing cryptonote outputs (step 2/2 of the full-chain membership proof migration)
80050 / 2847320 blocks (2% of step 2/2)2)
```

### PR DESCRIPTION
**Pull request by jeetrex17**
Fixes #149.

Clear migration progress lines using the actual printed width so trailing characters are not left behind during the LMDB migration.

### CODE REVIEW

File: src/blockchain_db/lmdb/db_lmdb.cpp [hunk 1]
```diff
@@ -7373,8 +7381,8 @@ void BlockchainLMDB::migrate_5_6()
 
         ++i;
         if (i == n_blocks)
-          std::cout << "\r                                                           \r" << std::flush; // erase the % print
-        //std::cout << "  3000000 / 3000000 blocks (100% of step 2/2)\r" << std::flush; // just showing that chars are erased effectively
+          LOGIF(el::Level::Info)
```
Comment (j-berman) [inline src/blockchain_db/lmdb/db_lmdb.cpp]:
```suggestion
          if (progress_width)
```

**Review by j-berman — COMMENTED** [review]
Small suggestion for consistency. This solution looks good to me generally, will be good to test with the beta stressnet.

**Review by j-berman — APPROVED** [review]
